[package]
name = "uninstall"
version = "2.2.3"
edition = "2021"


[dependencies]
whiskers-launcher-rs = { git = "https://github.com/Whiskers-Apps/whiskers-launcher-rs"}
fs_extra = "1.3.0"
sysinfo = "0.30.12"