[package]
name = "uninstall"
version = "1.1.1"
edition = "2021"


[dependencies]
whiskers-launcher-rs = { git = "https://github.com/lighttigerXIV/whiskers-launcher-rs"}
fs_extra = "1.3.0"

[target.'cfg(target_os = "windows")'.dependencies]
powershell_script = "1.1.0"
is_elevated = "0.1.2"